//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHKArtikelVarianten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHKArtikelVarianten()
        {
            this.KHKPreislistenArtikel = new HashSet<KHKPreislistenArtikel>();
        }
    
        public string Artikelnummer { get; set; }
        public short Mandant { get; set; }
        public int AuspraegungID { get; set; }
        public string EANNummer { get; set; }
        public string ABCKlasse { get; set; }
        public Nullable<decimal> Lagerbestand { get; set; }
        public Nullable<decimal> LagerbestandOhneDispo { get; set; }
        public Nullable<decimal> LagerbestandVerfuegbar { get; set; }
        public Nullable<decimal> Gewicht { get; set; }
        public Nullable<decimal> GewichtLME { get; set; }
        public Nullable<decimal> LetzterEK { get; set; }
        public Nullable<decimal> MittlererEK { get; set; }
        public Nullable<decimal> KalkulatorischerEK { get; set; }
        public Nullable<decimal> LetzterFEK { get; set; }
        public Nullable<short> HatZubehoer { get; set; }
        public Nullable<short> EARMeldepflicht { get; set; }
        public string EARRegNr { get; set; }
        public string EARMarke { get; set; }
        public string EARKategorie { get; set; }
        public string EARGeraeteart { get; set; }
        public string EARProduktgruppe { get; set; }
        public Nullable<decimal> EARGewicht { get; set; }
        public string FormelID { get; set; }
        public string Hauptlieferant { get; set; }
        public string LetzterLieferant { get; set; }
        public Nullable<short> Dispoformel { get; set; }
        public Nullable<decimal> Dispofaktor { get; set; }
        public Nullable<decimal> Bestellmenge { get; set; }
        public Nullable<int> Bestellzeitpunkt { get; set; }
        public Nullable<decimal> Meldebestand { get; set; }
        public Nullable<short> Wiederbeschaffungszeit { get; set; }
        public short WSIstWebshopArtikel { get; set; }
        public short WSIstVerkaufsArtikel { get; set; }
        public Nullable<System.DateTime> WSTerminVerkaufAb { get; set; }
        public Nullable<System.DateTime> WSTerminVerkaufBis { get; set; }
        public short WSIstSichtbar { get; set; }
        public short WSIstNeu { get; set; }
        public Nullable<System.DateTime> WSTerminNeuBis { get; set; }
        public short WSLagerAnzeige { get; set; }
        public short WSZeigeHersteller { get; set; }
        public string WSGuid { get; set; }
        public short WSIstGeaendert { get; set; }
        public short WSIstHauptbildGeaendert { get; set; }
        public short WSIstGalerieGeaendert { get; set; }
        public string WSAktuellesHauptbild { get; set; }
        public string WSAktuelleGaleriebilder { get; set; }
        public short WSIstStandardvariante { get; set; }
        public byte[] Timestamp { get; set; }
        public decimal WSMindestbestellmenge { get; set; }
        public decimal WSStaffelung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHKPreislistenArtikel> KHKPreislistenArtikel { get; set; }
    }
}
