//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHKPreislistenArtikel
    {
        public Nullable<short> Mandant { get; set; }
        public Nullable<int> ListeID { get; set; }
        public string Artikelnummer { get; set; }
        public Nullable<int> AuspraegungID { get; set; }
        public Nullable<decimal> AbMenge { get; set; }
        public Nullable<decimal> Einzelpreis { get; set; }
        public int ID { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual KHKArtikelVarianten KHKArtikelVarianten { get; set; }
        public virtual KHKPreislisten KHKPreislisten { get; set; }
    }
}
