//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHKPreislisten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHKPreislisten()
        {
            this.KHKPreislistenArtikel = new HashSet<KHKPreislistenArtikel>();
        }
    
        public int ID { get; set; }
        public short Mandant { get; set; }
        public string Bezeichnung { get; set; }
        public short IstAktion { get; set; }
        public Nullable<int> Basisliste { get; set; }
        public Nullable<int> Aktionsliste { get; set; }
        public Nullable<System.DateTime> GueltigVon { get; set; }
        public Nullable<System.DateTime> GueltigBis { get; set; }
        public short IstBruttopreis { get; set; }
        public short IstRabattfaehig { get; set; }
        public string Memo { get; set; }
        public string WKz { get; set; }
        public Nullable<short> DezimalstellenPreis { get; set; }
        public Nullable<short> Listentyp { get; set; }
        public short Aktiv { get; set; }
        public short WSAktiv { get; set; }
        public short WSIstGeaendert { get; set; }
        public string WSGuid { get; set; }
        public byte[] Timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHKPreislistenArtikel> KHKPreislistenArtikel { get; set; }
    }
}
