using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace amxDatenImport
{
    public static class amxImportHelper
    {

        public enum KHKTable
        {
            KHKArtikel
        }
        public enum KHKArtikelPropEnum
        {
            Artikelnummer,
            Mandant,
            Bezeichnung1,
            Bezeichnung2,
            Matchcode,
            Langtext,
            Dimensionstext,
            DimensionstextHTML,
            DimensionstextRTF,
            Memo,
            Artikelgruppe,
            Ersatzartikelnummer,
            Hersteller,
            HArtikelnummer,
            Steuerklasse,
            Erloescode,
            Wareneingangscode,
            Wareneinsatzcode,
            Warenbestandcode,
            SachkontoVK,
            SachkontoEK,
            SachkontoWZ,
            SachkontoWB,
            IstEinmalartikel,
            IstProvisionierbar,
            Nachweispflicht,
            Verkaufsmengeneinheit,
            MengenberechnungVK,
            DezimalstellenVK,
            UmrechnungsfaktorVK,
            VerpackungseinheitVK,
            UmrechnungsfaktorVPVK,
            PreiseinheitVK,
            Basismengeneinheit,
            DezimalstellenBasis,
            Lagermengeneinheit,
            DezimalstellenLager,
            UmrechnungsFaktorLME,
            Lagerfuehrung,
            Lagerplatzzuordnung,
            Gewichtseinheit,
            PreispflegeEK,
            IstBestellartikel,
            IstVerkaufsartikel,
            Stuecklistentyp,
            IstKundenkartei,
            IstLieferantenkartei,
            IstRabattfaehig,
            Gemeinkostenzuschlag,
            Bezugskostenzuschlag,
            Gewinnzuschlag,
            Bewertungssatz,
            Kostenstelle,
            Kostentraeger,
            IstFavorit,
            IstVorlage,
            Chargenpflicht,
            Warennummer,
            Ursprungsregion,
            Bestimmungsregion,
            Rabattgruppe,
            Laenge,
            Breite,
            Hoehe,
            IntrastatMengeneinheit,
            UmrechnungsfaktorIntraME,
            DezimalstellenIntraME,
            Hauptartikelgruppe,
            Vaterartikelgruppe,
            Grundpreiseinheit,
            UmrechnungsfaktorGP,
            GrundpreisBasis,
            PlatzID,
            Entnahmeverfahren,
            Variante,
            Inventurmethode,
            Aktiv,
            Artikelart,
            RessourcenRef,
            Zeichnungsnummer,
            GemeinkostenID,
            MinimaleLosgroesse,
            MaximaleLosgroesse,
            IstFertigungsartikel,
            IstUnterbaugruppe,
            IstErsatzteil,
            IstVerschleissteil,
            Schwundart,
            Schwund,
            PKonfigIstKonfigArtikel,
            PKonfigAnwendung,
            IstFremdleistung,
            KalkulationsLosgroesse,
            Ursprungsland,
            StatWertEingang,
            StatWertVersendung,
            Eigenmasse,
            StatVerfahren,
            DezimalstellenPreis,
            Verbrauchsteuer,
            Besteuerungsart,
            LangtextHTML,
            LangtextRTF,
            Herkunft,
            Timestamp
        }

        public enum KHKArtikelVariantenPropEnum
        {
            Artikelnummer,
            Mandant,
            AuspraegungID,
            EANNummer,
            ABCKlasse,
            Lagerbestand,
            LagerbestandOhneDispo,
            LagerbestandVerfuegbar,
            Gewicht,
            GewichtLME,
            LetzterEK,
            MittlererEK,
            KalkulatorischerEK,
            LetzterFEK,
            HatZubehoer,
            EARMeldepflicht,
            EARRegNr,
            EARMarke,
            EARKategorie,
            EARGeraeteart,
            EARProduktgruppe,
            EARGewicht,
            FormelID,
            Hauptlieferant,
            LetzterLieferant,
            Dispoformel,
            Dispofaktor,
            Bestellmenge,
            Bestellzeitpunkt,
            Meldebestand,
            Wiederbeschaffungszeit,
            WSIstWebshopArtikel,
            WSIstVerkaufsArtikel,
            WSTerminVerkaufAb,
            WSTerminVerkaufBis,
            WSIstSichtbar,
            WSIstNeu,
            WSTerminNeuBis,
            WSLagerAnzeige,
            WSZeigeHersteller,
            WSGuid,
            WSIstGeaendert,
            WSIstHauptbildGeaendert,
            WSIstGalerieGeaendert,
            WSAktuellesHauptbild,
            WSAktuelleGaleriebilder,
            WSIstStandardvariante,
            Timestamp,
            WSMindestbestellmenge,
            WSStaffelung
        }

        public static IEnumerable<string> getPropertyStrings(Type type)
        {
            List<string> stringlist = new List<string>();
            type.GetProperties().ToList().ForEach(x => stringlist.Add(x.Name));

            return stringlist;
        }
    }
}
