//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenDreamsRessourcenImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class amxImportRL
    {
        public string Typ { get; set; }
        public string ArtikelnummerNeu { get; set; }
        public string Artikelnummer { get; set; }
        public string Matchcode { get; set; }
        public string M1 { get; set; }
        public Nullable<double> A1 { get; set; }
        public string M2 { get; set; }
        public Nullable<double> A2 { get; set; }
        public string M3 { get; set; }
        public Nullable<double> A3 { get; set; }
        public string M4 { get; set; }
        public Nullable<double> A4 { get; set; }
        public string M5 { get; set; }
        public Nullable<double> A5 { get; set; }
        public string M6 { get; set; }
        public Nullable<double> A6 { get; set; }
        public string M7 { get; set; }
        public Nullable<double> A7 { get; set; }
        public string M8 { get; set; }
        public Nullable<double> A8 { get; set; }
        public string M9 { get; set; }
        public Nullable<double> A9 { get; set; }
        public string M10 { get; set; }
        public Nullable<double> A10 { get; set; }
        public string M11 { get; set; }
        public Nullable<double> A11 { get; set; }
        public string M12 { get; set; }
        public Nullable<double> A12 { get; set; }
        public string M13 { get; set; }
        public Nullable<double> A13 { get; set; }
        public string M14 { get; set; }
        public Nullable<double> A14 { get; set; }
        public string M15 { get; set; }
        public Nullable<double> A15 { get; set; }
        public string M16 { get; set; }
        public Nullable<double> A16 { get; set; }
        public string M17 { get; set; }
        public Nullable<double> A17 { get; set; }
        public string M18 { get; set; }
        public Nullable<double> A18 { get; set; }
        public string M19 { get; set; }
        public Nullable<double> A19 { get; set; }
        public string M20 { get; set; }
        public Nullable<double> A20 { get; set; }
        public string M21 { get; set; }
        public Nullable<double> A21 { get; set; }
        public string M22 { get; set; }
        public Nullable<double> A22 { get; set; }
        public string M23 { get; set; }
        public Nullable<double> A23 { get; set; }
        public string M24 { get; set; }
        public Nullable<double> A24 { get; set; }
        public string M25 { get; set; }
        public Nullable<double> A25 { get; set; }
        public string M26 { get; set; }
        public Nullable<double> A26 { get; set; }
        public string M27 { get; set; }
        public Nullable<double> A27 { get; set; }
        public string M28 { get; set; }
        public Nullable<double> A28 { get; set; }
        public string M29 { get; set; }
        public Nullable<double> A29 { get; set; }
        public string M30 { get; set; }
        public Nullable<double> A30 { get; set; }
        public string M31 { get; set; }
        public Nullable<double> A31 { get; set; }
        public string M32 { get; set; }
        public Nullable<double> A32 { get; set; }
        public string M33 { get; set; }
        public Nullable<double> A33 { get; set; }
        public string M34 { get; set; }
        public Nullable<double> A34 { get; set; }
        public string M35 { get; set; }
        public Nullable<double> A35 { get; set; }
        public string M36 { get; set; }
        public Nullable<double> A36 { get; set; }
        public string M37 { get; set; }
        public Nullable<double> A37 { get; set; }
        public string M38 { get; set; }
        public Nullable<double> A38 { get; set; }
        public string M39 { get; set; }
        public Nullable<double> A39 { get; set; }
        public string M40 { get; set; }
        public Nullable<double> A40 { get; set; }
        public string M41 { get; set; }
        public Nullable<double> A41 { get; set; }
        public string M42 { get; set; }
        public Nullable<double> A42 { get; set; }
    }
}
