//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenDreamsRessourcenImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHKArtikel
    {
        public string Artikelnummer { get; set; }
        public short Mandant { get; set; }
        public string Bezeichnung1 { get; set; }
        public string Bezeichnung2 { get; set; }
        public string Matchcode { get; set; }
        public string Langtext { get; set; }
        public string Dimensionstext { get; set; }
        public string DimensionstextHTML { get; set; }
        public string DimensionstextRTF { get; set; }
        public string Memo { get; set; }
        public string Artikelgruppe { get; set; }
        public string Ersatzartikelnummer { get; set; }
        public string Hersteller { get; set; }
        public string HArtikelnummer { get; set; }
        public Nullable<short> Steuerklasse { get; set; }
        public Nullable<short> Erloescode { get; set; }
        public Nullable<short> Wareneingangscode { get; set; }
        public Nullable<short> Wareneinsatzcode { get; set; }
        public Nullable<short> Warenbestandcode { get; set; }
        public string SachkontoVK { get; set; }
        public string SachkontoEK { get; set; }
        public string SachkontoWZ { get; set; }
        public string SachkontoWB { get; set; }
        public short IstEinmalartikel { get; set; }
        public short IstProvisionierbar { get; set; }
        public Nullable<short> Nachweispflicht { get; set; }
        public string Verkaufsmengeneinheit { get; set; }
        public string MengenberechnungVK { get; set; }
        public Nullable<short> DezimalstellenVK { get; set; }
        public Nullable<decimal> UmrechnungsfaktorVK { get; set; }
        public string VerpackungseinheitVK { get; set; }
        public Nullable<decimal> UmrechnungsfaktorVPVK { get; set; }
        public Nullable<short> PreiseinheitVK { get; set; }
        public string Basismengeneinheit { get; set; }
        public Nullable<short> DezimalstellenBasis { get; set; }
        public string Lagermengeneinheit { get; set; }
        public Nullable<short> DezimalstellenLager { get; set; }
        public Nullable<decimal> UmrechnungsFaktorLME { get; set; }
        public short Lagerfuehrung { get; set; }
        public short Lagerplatzzuordnung { get; set; }
        public string Gewichtseinheit { get; set; }
        public Nullable<short> PreispflegeEK { get; set; }
        public short IstBestellartikel { get; set; }
        public short IstVerkaufsartikel { get; set; }
        public Nullable<short> Stuecklistentyp { get; set; }
        public short IstKundenkartei { get; set; }
        public short IstLieferantenkartei { get; set; }
        public short IstRabattfaehig { get; set; }
        public Nullable<decimal> Gemeinkostenzuschlag { get; set; }
        public Nullable<decimal> Bezugskostenzuschlag { get; set; }
        public Nullable<decimal> Gewinnzuschlag { get; set; }
        public string Bewertungssatz { get; set; }
        public string Kostenstelle { get; set; }
        public string Kostentraeger { get; set; }
        public short IstFavorit { get; set; }
        public short IstVorlage { get; set; }
        public Nullable<short> Chargenpflicht { get; set; }
        public string Warennummer { get; set; }
        public string Ursprungsregion { get; set; }
        public string Bestimmungsregion { get; set; }
        public string Rabattgruppe { get; set; }
        public Nullable<decimal> Laenge { get; set; }
        public Nullable<decimal> Breite { get; set; }
        public Nullable<decimal> Hoehe { get; set; }
        public string IntrastatMengeneinheit { get; set; }
        public Nullable<decimal> UmrechnungsfaktorIntraME { get; set; }
        public Nullable<short> DezimalstellenIntraME { get; set; }
        public string Hauptartikelgruppe { get; set; }
        public string Vaterartikelgruppe { get; set; }
        public string Grundpreiseinheit { get; set; }
        public Nullable<decimal> UmrechnungsfaktorGP { get; set; }
        public Nullable<decimal> GrundpreisBasis { get; set; }
        public Nullable<int> PlatzID { get; set; }
        public string Entnahmeverfahren { get; set; }
        public string Variante { get; set; }
        public Nullable<short> Inventurmethode { get; set; }
        public short Aktiv { get; set; }
        public Nullable<short> Artikelart { get; set; }
        public string RessourcenRef { get; set; }
        public string Zeichnungsnummer { get; set; }
        public string GemeinkostenID { get; set; }
        public Nullable<decimal> MinimaleLosgroesse { get; set; }
        public Nullable<decimal> MaximaleLosgroesse { get; set; }
        public short IstFertigungsartikel { get; set; }
        public short IstUnterbaugruppe { get; set; }
        public short IstErsatzteil { get; set; }
        public short IstVerschleissteil { get; set; }
        public string Schwundart { get; set; }
        public decimal Schwund { get; set; }
        public short PKonfigIstKonfigArtikel { get; set; }
        public string PKonfigAnwendung { get; set; }
        public short IstFremdleistung { get; set; }
        public decimal KalkulationsLosgroesse { get; set; }
        public string Ursprungsland { get; set; }
        public Nullable<decimal> StatWertEingang { get; set; }
        public Nullable<decimal> StatWertVersendung { get; set; }
        public Nullable<decimal> Eigenmasse { get; set; }
        public Nullable<short> StatVerfahren { get; set; }
        public short DezimalstellenPreis { get; set; }
        public short Verbrauchsteuer { get; set; }
        public short Besteuerungsart { get; set; }
        public string LangtextHTML { get; set; }
        public string LangtextRTF { get; set; }
        public Nullable<short> Herkunft { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
