//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenDreamsRessourcenImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHKPpsArbeitsgaenge
    {
        public string Arbeitsgangnummer { get; set; }
        public short Mandant { get; set; }
        public string Bezeichnung1 { get; set; }
        public string Bezeichnung2 { get; set; }
        public string Matchcode { get; set; }
        public string Memo { get; set; }
        public string Dimensionstext { get; set; }
        public string Ruestzeittext { get; set; }
        public Nullable<decimal> Ruestzeit { get; set; }
        public string Stueckzeittext { get; set; }
        public Nullable<decimal> Stueckzeit { get; set; }
        public Nullable<decimal> Umrechnungsfaktor { get; set; }
        public string TransportzeitFremdText { get; set; }
        public Nullable<decimal> TransportzeitFremd { get; set; }
        public string StueckzeitFremdText { get; set; }
        public Nullable<decimal> StueckzeitFremd { get; set; }
        public string Lieferant { get; set; }
        public string Artikelnummer { get; set; }
        public int AuspraegungId { get; set; }
        public Nullable<decimal> Planzeit { get; set; }
        public string Planzeittext { get; set; }
        public string Arbeitsplatznummer { get; set; }
        public Nullable<decimal> Pufferzeit { get; set; }
        public string Pufferzeittext { get; set; }
        public string Ueberlappungzeittext { get; set; }
        public Nullable<decimal> Ueberlappungzeit { get; set; }
        public Nullable<decimal> Ueberlappungmenge { get; set; }
        public string Ueberlappungtyp { get; set; }
        public Nullable<decimal> Ueberlappungprozent { get; set; }
        public string AusfuehrungsArt { get; set; }
        public Nullable<short> DefaultRessourceTyp { get; set; }
        public string DefaultRessourceNummer { get; set; }
        public short Aktiv { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
