//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenDreamsRessourcenImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHKPpsRessourcenPositionen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHKPpsRessourcenPositionen()
        {
            this.KHKPpsRessourcenAGPositionen = new HashSet<KHKPpsRessourcenAGPositionen>();
        }
    
        public string Artikelnummer { get; set; }
        public string Variante { get; set; }
        public int AuspraegungIDKopf { get; set; }
        public short Mandant { get; set; }
        public short Position { get; set; }
        public string Ressourcetyp { get; set; }
        public string Ressourcenummer { get; set; }
        public string Arbeitsgangnummer { get; set; }
        public string Matchcode { get; set; }
        public string Dimensionstext { get; set; }
        public Nullable<decimal> Menge { get; set; }
        public Nullable<int> MengeNKS { get; set; }
        public string MengeBerechnung { get; set; }
        public string MengeDimensionen { get; set; }
        public Nullable<decimal> Umrechnungsfaktor { get; set; }
        public short IstEinmalmenge { get; set; }
        public string Ruestzeittext { get; set; }
        public Nullable<decimal> Ruestzeit { get; set; }
        public string Stueckzeittext { get; set; }
        public Nullable<decimal> Stueckzeit { get; set; }
        public string Pufferzeittext { get; set; }
        public Nullable<decimal> Pufferzeit { get; set; }
        public string Ueberlappungzeittext { get; set; }
        public Nullable<decimal> Ueberlappungzeit { get; set; }
        public Nullable<decimal> Ueberlappungmenge { get; set; }
        public Nullable<decimal> Preis { get; set; }
        public string Lagermengeneinheit { get; set; }
        public string Transportzeittext { get; set; }
        public Nullable<decimal> Transportzeit { get; set; }
        public string AusfuehrungsArtAG { get; set; }
        public Nullable<int> AuspraegungID { get; set; }
        public Nullable<int> PlatzID { get; set; }
        public int BelPosID { get; set; }
        public short IstGeloescht { get; set; }
        public short IstOffen { get; set; }
        public Nullable<int> PositionExtern { get; set; }
        public string PositionExternPraefix { get; set; }
        public string PositionExternSuffix { get; set; }
        public string Materialteileart { get; set; }
        public string Auspraegungstyp { get; set; }
        public Nullable<decimal> Planzeit { get; set; }
        public string Planzeittext { get; set; }
        public string Ueberlappungtyp { get; set; }
        public Nullable<decimal> Ueberlappungprozent { get; set; }
        public Nullable<decimal> MengeNach { get; set; }
        public Nullable<short> IstTextuebergabe { get; set; }
        public short IstCadFixPos { get; set; }
        public string PosVariante { get; set; }
        public string PositionCAD { get; set; }
        public Nullable<int> Anzahl { get; set; }
        public string FormelID { get; set; }
        public Nullable<decimal> DIM1 { get; set; }
        public Nullable<decimal> DIM2 { get; set; }
        public Nullable<decimal> DIM3 { get; set; }
        public string Fremdfertiger { get; set; }
        public Nullable<decimal> SollEinzelpreis { get; set; }
        public Nullable<decimal> Leistungsgrad { get; set; }
        public Nullable<short> RessourceTypAg { get; set; }
        public string RessourceNummerAg { get; set; }
        public string PositionExternAnzeige { get; set; }
        public short KapazAnzahlMax { get; set; }
        public decimal MindestmengeAG { get; set; }
        public byte[] Timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHKPpsRessourcenAGPositionen> KHKPpsRessourcenAGPositionen { get; set; }
    }
}
