//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenDreamsRessourcenImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHKPpsRessourcenkopf
    {
        public string Artikelnummer { get; set; }
        public string Variante { get; set; }
        public short Mandant { get; set; }
        public string Bezeichnung1 { get; set; }
        public string Bezeichnung2 { get; set; }
        public string Matchcode { get; set; }
        public string Memo { get; set; }
        public string Zeichnungsnummer { get; set; }
        public Nullable<decimal> VonMenge { get; set; }
        public Nullable<decimal> BisMenge { get; set; }
        public Nullable<System.DateTime> VonDatum { get; set; }
        public Nullable<System.DateTime> BisDatum { get; set; }
        public short IstOffen { get; set; }
        public string Klassenummer { get; set; }
        public short IstFremdfertigung { get; set; }
        public string KundenKto { get; set; }
        public Nullable<int> VariantenID { get; set; }
        public Nullable<short> IstDefault { get; set; }
        public string Preisfindung { get; set; }
        public string Variantengruppe { get; set; }
        public Nullable<decimal> Menge { get; set; }
        public Nullable<decimal> VKPreis { get; set; }
        public Nullable<System.DateTime> Fertigdatum { get; set; }
        public Nullable<int> LieferBelID { get; set; }
        public string Status { get; set; }
        public Nullable<short> StatIndex { get; set; }
        public int AuspraegungID { get; set; }
        public string DimText { get; set; }
        public Nullable<short> Produktionszeit { get; set; }
        public Nullable<decimal> UmrechnungsfaktorPZ { get; set; }
        public string Sprache { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
