//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenDreamsRessourcenImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHKTan
    {
        public string Tabelle { get; set; }
        public short Mandant { get; set; }
        public Nullable<int> Tan { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
